#!/bin/bash

if [ ! -f raspi-config ]; then
  echo ""
  echo "raspi-config not found in current directory"
  echo ""
  exit 1
fi

if [ `grep -c 'ROOT_DEV1="${ROOT_PART:0:(${#ROOT_PART} - 1)}"' raspi-config` -ne 0 ]; then
  echo ""
  echo "raspi-config already patched"
  echo ""
  exit 1
fi

echo ""
echo -n "Ok to patch raspi-config (y/n)? "
while read -r -n 1 -s answer; do
  if [[ ${answer} = [yYnN] ]]; then
    echo "${answer}"
    if [[ ${answer} = [yY] ]]; then
      break
    else
      echo ""
      echo "Aborted"
      echo ""
      exit 1
    fi
  fi
done

cp raspi-config raspi-config-original
echo ""
echo "raspi-config copied to raspi-config-original"

echo ""
echo "Patching raspi-config"

sed -i 's|#!/bin/sh|#!/bin/bash|' raspi-config

sed -i 's|  PART_NUM=${ROOT_PART#mmcblk0p}|  ROOT_DEV1="${ROOT_PART:0:(${#ROOT_PART} - 1)}"\n  ROOT_DEV2="${ROOT_DEV1}"\
  if [ "${ROOT_DEV2}" = "mmcblk0p" ]; then\n    ROOT_DEV2="${ROOT_DEV2:0:(${#ROOT_DEV2} - 1)}"\n  fi\n  PART_NUM=${ROOT_PART#${ROOT_DEV1}}|' raspi-config

sed -i 's|  LAST_PART_NUM=$(parted /dev/mmcblk0 -ms unit s p |  LAST_PART_NUM=$(parted /dev/${ROOT_DEV2} -ms unit s p |' raspi-config

sed -i 's|  PART_START=$(parted /dev/mmcblk0 -ms unit s p |  PART_START=$(parted /dev/${ROOT_DEV2} -ms unit s p |' raspi-config

sed -i 's|  fdisk /dev/mmcblk0 <<EOF|  fdisk /dev/${ROOT_DEV2} <<EOF|' raspi-config

sed -i 's|    resize2fs /dev/$ROOT_PART &&|    ROOT_DEV=\\$(findmnt / -o source -n) \&\&\n    resize2fs \\$ROOT_DEV \&\&|' raspi-config

sed -i 's|cat /proc/device-tree/model|cat /proc/device-tree/model \| tr -d '\''\\0'\''|' raspi-config

echo ""
echo "Patching completed"
echo ""
