#!/bin/bash

if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
  SYSTEMD=1
elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
  SYSTEMD=0
else
  echo ""
  echo "Unrecognized init system"
  echo ""
  exit 1
fi

if [ ${SYSTEMD} -eq 1 ]; then
  ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
else
  if [ ! -h /dev/root ]; then
    echo ""
    echo "/dev/root does not exist or is not a symlink"
    echo ""
    exit 1
  fi
  ROOT_PART=$(readlink /dev/root)
fi

if [ "${ROOT_PART}" = "mmcblk0p2" ]; then
  raspi-config
else
  ROOT_DEV="${ROOT_PART:0:(${#ROOT_PART} - 1)}"
  cp /usr/bin/raspi-config /tmp/raspi-config-usb-tmp
  sed -i -E "s/mmcblk0p?/${ROOT_DEV}/" /tmp/raspi-config-usb-tmp
  sed -i 's|    resize2fs /dev/$ROOT_PART &&|    ROOT_DEV=\\$(findmnt / -o source -n) \&\&\n    resize2fs \\$ROOT_DEV \&\&|' /tmp/raspi-config-usb-tmp
  /tmp/raspi-config-usb-tmp
  rm /tmp/raspi-config-usb-tmp
fi
